services:

  frontend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ${VOLUMES:--}/src:/app/src
      - ${VOLUMES:--}/public:/app/public
    ports:
      - "9000:8080"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    command: >
      sh -c "if [ \"$NODE_ENV\" = \"production\" ]; then 
        npm install -g serve && npm run build && serve -s dist -l 8080; 
        else npm start; 
        fi"
