services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./node_modules:/app/node_modules
    ports:
      - "9000:8080"
    environment:
      - NODE_ENV=development
