services:
  gc_registry:
    restart: always
    image: gc_registry:latest
    build:
      context: ./
      dockerfile: "Dockerfile"
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    ports:
      - "8080:8080"
      - "9000:9000"