services:
  gc_registry:
    restart: no
    env_file:
      - .env
      - .env.ci
    environment:
      - TC_HOST=host.docker.internal
      - POSTGRES_DB=registry
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - DATABASE_URL=postgresql://postgres:password@db_write/write
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - db_write

  db_write:
    image: postgres:13
    environment:
      - POSTGRES_DB=registry
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password