services:
  gc_registry:
    restart: no
    env_file:
      - .env
      - .env.ci
    environment:
      - TC_HOST=host.docker.internal
      - POSTGRES_DB=gc_registry
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - DATABASE_URL=postgresql://postgres:password@db_write/gc_registry
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - db_write
      - db_read

  db_write:
    image: postgres:13
    environment:
      - POSTGRES_DB=gc_registry
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  db_read:
    image: postgres:13
    environment:
      - POSTGRES_DB=gc_registry
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  eventstore.db:
    image: eventstore/eventstore:release-v5
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=True
      - EVENTSTORE_DB=/var/lib/eventstore-data
      - EVENTSTORE_INDEX=/var/lib/eventstore-index
      - EVENTSTORE_LOG=/var/log/eventstore
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore-data
      - type: volume
        source: eventstore-volume-index
        target: /var/lib/eventstore-index
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore