version: '3.8'

services:
  eventstore.db:
    image: eventstore/eventstore:23.10.2-bookworm-slim
    ports:
      - "2114:2114"
      - "1113:1113"
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_HTTP_PORT=2114
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_TELEMETRY_OPTOUT=true
      - DOTNET_EnableWriteXorExecute=0
      - EVENTSTORE_ADVERTISE_HOST_TO_CLIENT_AS=localhost
      - EVENTSTORE_ADVERTISE_NODE_PORT_TO_CLIENT_AS=2114
      - EVENTSTORE_NODE_PORT=2114
      - EVENTSTORE_NODE_TCP_PORT=1113
    volumes:
      - type: volume
        source: eventstore_data
        target: /var/lib/eventstore
        volume:
          nocopy: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:2114/health/live || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  gc_registry:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - ESDB_CONNECTION_STRING=eventstore.db
    depends_on:
      - eventstore.db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - gc_registry

volumes:
  eventstore_data: 