services:
  gc_registry:
    build:
      context: ./
      dockerfile: "Dockerfile"
    volumes:
      - "./:/gc_registry"
    ports:
      - "80:80"
    environment:
      - DATABASE_URL_WRITE=db_write
      - DATABASE_URL_READ=db_read
      - DATABASE_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - DB_TEST_FP=None
      - ENVIRONMENT=PROD
      - JWT_SECRET_KEY=secret_key
      - JWT_ALGORITHM=HS256 
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - REFRESH_WARNING_MINS=5
      - STATIC_DIR_FP=/src/api/static
      - MIDDLEWARE_SECRET_KEY=secret_key
    depends_on:
      - db_write
      - db_read

  db_write:
    image: postgres:13
    volumes:
      - postgres_data_write:/var/lib/postgresql/data

  db_read:
    image: postgres:13
    volumes:
      - postgres_data_read:/var/lib/postgresql/data

volumes:
  gc_registry:
  postgres_data_write:
  postgres_data_read: