name: CI

on:
  push:
  workflow_dispatch:

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Setup env vars
        run: cp .env.example .env

      - name: CI specific env vars
        run: |
            touch .env.ci
            echo "${{ secrets.CI_ENV_VARS }}" > .env.ci

      - name: Build Docker container
        run: docker compose build

      - name: Run CI tasks
        run: docker compose -f compose.yml -f compose.ci.yml run -i -T --rm gc_registry make ci

      - name: Store coverage files
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ./code/coverage.xml
            
  publish:
    name: "Publish Unit Test Results"
    needs: quality
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Test Results
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: ./coverage.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2

        if: always()
        with:
          junit_files: "./coverage.xml"
          comment_mode: always
          check_name: "Unit Tests Results"

      - name: Write to Job Summary
        run: cat ./coverage.xml >> $GITHUB_STEP_SUMMARY

      - name: Publish coverage as PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Unit Tests Code Coverage
          path: ./coverage.xml

