name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ELASTIC_BEANSTALK_APPLICATION: gc-registry
  ELASTIC_BEANSTALK_ENVIRONMENT: gc-registry-prod3
  S3_BUCKET: elasticbeanstalk-us-east-1-996119908566

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: |
          npm install
          npm run build

      - name: Create deployment package
        run: |
          # Create a zip file with the correct path separators
          zip -r ../app.zip . -x "*.git*" "node_modules/*" "*.zip"

      - name: Upload to S3
        run: |
          aws s3 cp app.zip s3://${{ env.S3_BUCKET }}/${{ env.ELASTIC_BEANSTALK_APPLICATION }}/${{ github.sha }}.zip

      - name: Create Elastic Beanstalk version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name ${{ env.ELASTIC_BEANSTALK_APPLICATION }} \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket="${{ env.S3_BUCKET }}",S3Key="${{ env.ELASTIC_BEANSTALK_APPLICATION }}/${{ github.sha }}.zip"

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name ${{ env.ELASTIC_BEANSTALK_ENVIRONMENT }} \
            --version-label ${{ github.sha }} 